import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import chalk from 'chalk';
import { execa } from 'execa';

async function git(cwd, args) {
  const { stdout } = await execa('git', args, { cwd });
  return stdout.trim();
}

async function fileExists(filePath) {
  try {
    await fs.stat(filePath);
    return true;
  } catch {
    return false;
  }
}

async function createDemoRepo() {
  const demoDir = path.join(os.tmpdir(), `devflow-demo-${Date.now()}`);
  await fs.mkdir(path.join(demoDir, 'src'), { recursive: true });

  // Initialize repo
  await git(demoDir, ['init']);
  await git(demoDir, ['config', 'user.email', 'devflow-demo@example.com']);
  await git(demoDir, ['config', 'user.name', 'DevFlow Demo']);

  // Base files
  await fs.writeFile(
    path.join(demoDir, 'src', 'app.js'),
    [
      "export function run(input) {",
      "  // Baseline: safe behavior",
      "  return String(input).trim();",
      "}",
      "",
    ].join('\n'),
    'utf8'
  );

  await fs.writeFile(
    path.join(demoDir, 'src', 'auth.js'),
    [
      "export function isAllowed(user) {",
      "  return Boolean(user);",
      "}",
      "",
    ].join('\n'),
    'utf8'
  );

  await fs.writeFile(
    path.join(demoDir, 'README.md'),
    [
      "# DevFlow Judge Demo",
      "",
      "This repo is auto-generated by `devflow demo --setup`.",
      "",
    ].join('\n'),
    'utf8'
  );

  await git(demoDir, ['add', '-A']);
  await git(demoDir, ['commit', '-m', 'chore: initial demo']);

  // Create staged change with fake secret (redaction demo)
  await fs.writeFile(
    path.join(demoDir, 'src', 'auth.js'),
    [
      "// Intentionally includes a fake token to demonstrate redaction in DevFlow prompts.",
      "const GITHUB_TOKEN = 'ghp_1234567890abcdefghijklmnopqrstuvwxyz';",
      "",
      "export function isAllowed(user) {",
      "  return Boolean(user) && GITHUB_TOKEN.length > 0;",
      "}",
      "",
    ].join('\n'),
    'utf8'
  );
  await git(demoDir, ['add', 'src/auth.js']);

  // Create unstaged change with an obvious issue (review/audit demo)
  await fs.writeFile(
    path.join(demoDir, 'src', 'app.js'),
    [
      "export function run(input) {",
      "  // WARNING: intentionally insecure pattern for demo purposes.",
      "  // Example: eval injection risk.",
      "  return eval(String(input));",
      "}",
      "",
    ].join('\n'),
    'utf8'
  );

  return demoDir;
}

export class DemoCommand {
  async execute(options = {}) {
    console.log(chalk.cyan('🎬 DevFlow Demo (Judge Mode)'));

    const shouldSetup = Boolean(options.setup);
    const open = Boolean(options.open);

    let demoDir = options.dir;

    if (shouldSetup) {
      try {
        demoDir = await createDemoRepo();
        console.log(chalk.green('✔ Demo repository created'));
      } catch (e) {
        console.log(chalk.red('✖ Failed to create demo repository. Ensure git is installed.'));
        console.log(chalk.dim(String(e?.message || e)));
        process.exitCode = 1;
        return;
      }
    }

    if (!demoDir) {
      demoDir = process.cwd();
      const hasGit = await fileExists(path.join(demoDir, '.git'));
      if (!hasGit) {
        console.log(chalk.yellow('⚠ No demo repo selected and current folder is not a git repository.'));
        console.log(chalk.dim('Tip: run: devflow demo --setup'));
      }
    }

    const quoted = demoDir.includes(' ') ? `"${demoDir}"` : demoDir;

    console.log('');
    console.log(chalk.white('Recommended 60-second judge script:'));
    console.log(chalk.dim(`  cd ${quoted}`));
    console.log(chalk.dim('  devflow doctor'));
    console.log(chalk.dim('  devflow review --all --dry-run --max-chars 6000'));
    console.log(chalk.dim('  devflow audit --all --format markdown --language en --dry-run --max-chars 8000'));
    console.log(chalk.dim('  devflow commit --dry-run   # (uses staged diff)'));
    console.log('');

    console.log(chalk.white('Notes:'));
    console.log(chalk.dim('- `--dry-run` prevents launching `gh copilot` (prompt is still copied/printed).'));
    console.log(chalk.dim('- Secrets are redacted automatically in prompts.'));

    if (open) {
      console.log('');
      console.log(chalk.yellow('Opening Copilot is disabled in demo mode by default.'));
      console.log(chalk.dim('Remove --dry-run to launch `gh copilot` after each command.'));
    }
  }
}
